Dockerfile

Hi @tomsquest,
thanks for your awesome docker image.
I'm using it with the new htpasswd authentication introduced in 2.0 in bcrypt mode.
Radicale requires the passlib for bcrypt to allow bcrypt htpasswd files.
The changes in this pull request allow users to use htpasswd-files with secure bcrypt.
Best,
Enno

Add bcrypt support

---

Dockerfile
README.md

Supersedes #9 
We want non-conflictual user id between host and container.
Done:
* hardcode the user/group ID: Chosen value: 2999
* Let's the hoster, rebuild the image with its own UID/GID

Can override the default user/group ID when building

---

Dockerfile

Explicity set the version of radicale so that changes to the version (and hence commits), trigger dockerhub builds. 
Also for building/testing locally, changing the version breaks the docker cache, forcing a full rebuild.

Explicitly set the version of Radicale

---

.travis.yml
config/config

This PR restores the default configuration settings to a more pristine version (ie. Radicale official config).
Our config file still has:
* `hosts`: must be _opened_ for the container to accept connections from the host
* `filesystem_folder` to point to the `/data` dir/volume
Previously I had disabled the default UI of Radicale v2 in the embedded config file.
The rights were also force to "none" (and its seems to already be the default).

Get back to the default configuration

---

Dockerfile
README.md
docker-entrypoint.sh

- Update to a newer and more specific version of python alpine (so the shadow package is available)
- Update the readme instructions
This gives people using the container another option for how they want to run it :)

Use usermod/groupmod to modify the user/group at runtime

---

Dockerfile

As documented at http://radicale.org/clients/#infcloud-caldavzap-and-carddavmate
[RadicaleInfCloud](https://github.com/Unrud/RadicaleInfCloud) added.

Integrate InfCloud into Radicale’s web interface

---

Dockerfile
README.md

This PR removes Tini and instructs to use the `--init` flag when running the container.
Tini is no more needed to handle processes as it is build in docker since version 1.13. From Tini repo:
> If you are using Docker 1.13 or greater, Tini is included in Docker itself. This includes all versions of Docker CE. To enable Tini, just pass the --init flag to docker run. 
> Source: https://github.com/krallin/tini#using-tini
@robertbeal what do you think?

Remove tini in favor of `--init`

---

Dockerfile

New minor release is out: https://github.com/Kozea/Radicale/releases/tag/2.1.9

Upgrade to 2.1.9

---

.gitignore
.travis.yml
Dockerfile
build.sh

This will build radicale in (currently) 4 different architectures using Travis.
- build.sh generates a Dockerfile for each "arch" simply using `sed` to change the base image at the top of the file.
- As a base image (for non amd64 builds) I've used resin's alpine images which have qemu installed
- This has meant installing `python3` and `python3-dev` as part of the build. This actually results in a smaller image (circa 40mb, as the `python3-dev` packages are removed once it is built which they weren't on the `python:3.6.4-alpine3.7` base image)
- You'll need to go into the Settings on your Travis build for radicale, and add two ENV variables, `DOCKER_USER` and `DOCKER_PWD` to allow Travis to push built images to your dockerhub account.
- Variables are now set and controlled in …

Multi-arch builds of radicale!

---

.travis.yml

Currently:
- on master change, new images are pushed as docker-radical:$ARCH and docker-radicale:$ARCH-$VERSION
Consequences:
- on master change, published images gets overwritten
- release version (eg. 2.1.10.0) are not released as multi-arch images
This PR does
- only push new images on tag (eg. new tag 2.1.10.0 pushed gives the multi-arch images being built and pushed)
Consequences:
- no images get pushed with version *exactly* matching the version of radicale (we have 2.1.10*.0*, radicale have only 2.1.10 (the last digit in our version is an increment of the Docker image, no Radicale itself)
close #30

Release on tag

---

.travis.yml

This PR fixes the duplicate version in travis.yml and the Dockerfile.
As we do not release a tag matching the exact version of Radicale, the version in travis.yml is superfluous (the Git tag is used to tag the images).

Set only version in the Dockerfile

---

Dockerfile
docker-entrypoint.sh
test_image.py

Make `/config` dir and `/config/config` file reaonly
- `root` owns `/config` and `/config/config`
- default `root` permissions are 664, ie. radicale can read the config file
Also fix permissions not being set for group `radicale`.
Close #33

feat: make config only readable

---

.travis.yml
Dockerfile
build.sh

Remove deprecated resin/ images and use balenalib/ in place.
Also, forced 3.9 of alpine for all archs.
@robertbeal can you have a look at this?

fix: multi-arch fails due to resin images deprecated on docker hub

---

Dockerfile

Hi,
running your docker for some time now. I have a redicale hook which is actually triggering phonebook sync of contacts in my home network. Since I updated that service to run on https the built in version of busybox/alpine wget is no longer working on the hook (because busybox not having linked its wget against ssl). A simple `apk add wget` would solve my problem. I've added it to the docker file. Would be great if you could merge it. 😃 
Cheers,
m.

added wget (as alpine/busybox default wget is not linked against ssl)

---

config

Hey first thanks for this amazing dockerfile - saved me a lot of work!
I only figured one problem when setting log level to `debug`: the container didn't start with exception `ERROR: Invalid configuration: Invalid option 'level' in section 'logging' in config`. I first was confused as that's what the radicale conf template suggest as well, but then I figured that since release 2.1.11 a couple of things changed in logger config. 
So IMHO the docker image conf template should align to the template of the release https://github.com/Kozea/Radicale/blob/8387a4c33f650d4392d6085750000f27ee51f278/config fix in that PR.

Use logging conf template from release

---

Dockerfile
README.md

Submitting my changes to your Dockerfile after I finally succeeded building an image with custom UID/GID on my Synology NAS.  
Signed-off-by: AdZero <adzero.git@gmail.com>

fix: add ENV variables to handle ARG values during image build process on Synology NAS

---

Dockerfile

Radicale requires pytz for timezone support. As is adding events with for example `DTSTART;TZID=Europe/Stockholm;VALUE=DATE-TIME:20200527T101010` results in `ERROR:root:No module named 'pytz'`, similar to here https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886425

Add pytz dependency

---

README.md
docker-entrypoint.sh

This PR adds the setup to use git cloning and pushing of your CalDAV/CardDAV files.
You need the following environment variables:
1. `GIT_REPOSITORY`: The repository URL, with username and password, example: `https://myuser:mypass@github.com/myuser/myrepo`
2. `GIT_USERNAME`: The username to be used for commits
3. `GIT_EMAIL`: The email to be used for commits
And enable the `hook` in your config file:
```
[storage]
hook = git add -A && (git diff --cached --quiet || git commit -m "Changes by "%(user)s) && git push origin master
```
This option is fully optional, if the environment variables are not defined, the git repository is not used.
Looking forward to your review :)

Integrate git cloning and pushing

---

.tool-versions
.travis.yml
CHANGELOG.md
Dockerfile
Pipfile
Pipfile.lock
README.md
ci/build-push.sh
config
test_image_custom_build.py
test_image_prod.py

Upgrade to latest radicale.
Also updated:
- Alpine
- Python
Image has been pushed with name `tomsquest/docker-radicale:v3-test`, so it can be pulled with:
```
docker pull tomsquest/docker-radicale:v3-test
```

Upgrade to Radicale v3.0.6

---

README.md

The imap plugin linked to until now (https://gitlab.com/comzeradd/radicale-imap) is not compatible with 3.0 anymore, while the original plugin from UnRud was updated: https://github.com/Unrud/RadicaleIMAP
This is quite nasty, because you don't even get a useful error message with `debug` level logging... just a 500 server error on login attempts.

Update IMAP plugin references for Radicale 3.0

---

README.md
ci/build-push.sh

- `i386` arch was not working due to a bug in the build script (was amd64), so I assume nobody was using it
- `arm` (not `arm64`) has problem building with balenalib images for some weird errors. So unless someone complains or I found a working base image, support is removed.

feat: only support amd64 and arm64 architectures (drop i386 and arm)

---

README.md
docker-compose.yml

This fixes a bug when trying to start the container using docker-compose. 
```
ERROR: for radicale  Cannot start service radicale: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/user/radicale/config" to rootfs at "/config" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
Also, I changed the path on the host to be relative to the docker-compose file so it no longer assumes the full path of the project.

Fix docker-compose volumes

---

docker-entrypoint.sh

Using docker-radicale image in a hardened environment (for instance using "user: 2999" in docker-compose.yml) does not work since su-exec is always executed despite what user the container is running as (except root). su-exec always requires root anyway, so today docker-entrypoint.sh breaks the possibility to set container user before executing inside the container.
This pull request makes the image support setting user at build-time so container does not have to be started as root and then drop privileges using su-exec. For demo, Ihave created a container from my fork where the forked container is extended with files owned by the user id and group id matching the user field value in docker-compose.yml.
Example:
```
FROM hecd/docker-radicale:latest
COPY --chown=2999:2999 …
```

fix: support for running image as non-root without requiring dropping privileges using su-exec.

---

Dockerfile

Docker container currently doesn't contain an ssh binary and as thus when using a hook for git, ssh remotes cannot be used.  
This change should fix that

fix: add openssh for git ssh remotes

---

.github/workflows/build.yaml
.github/workflows/release.yaml
README.md

Updating Alpine to 3.17 blocked the release of the arm v7.
bcrypt need rusts which cause oom or network error downloading cargo indices.
There seems to be workaround when running in tmpfs or other strange stuff.
In all case, too complex to maintain, so I am dropping support for arm v7 (which is 32bits, so a bit old).

fix: drop support for arm v7

---

Dockerfile

Hi Tom, Thanks for your hard work on this.  I just noticed the following vulns are patched in alpine 3.17.3 so made a quick PR to bump the version.
```
tomsquest/docker-radicale:3.1.8.1 (alpine 3.17.2)
=================================================
Total: 18 (UNKNOWN: 0, LOW: 0, MEDIUM: 8, HIGH: 8, CRITICAL: 2)
┌────────────┬────────────────┬──────────┬───────────────────┬───────────────┬────────────────────────────────────────────────────────────┐
│  Library   │ Vulnerability  │ Severity │ Installed Version │ Fixed Version │                           Title                            │
├────────────┼────────────────┼──────────┼───────────────────┼───────────────┼────────────────────────────────────────────────────────────┤
│ curl       │ CVE-2023-27536 │ CRITICAL │ 7.87.0-r2         │ …
```

chore: Alpine version bump 3.17.2 -> 3.17.3 as 3.17.2 has 2 critical vulnerabilities

---

Dockerfile

Bump alpine to latest version to address vulnerabilities present in the existing alpine base image version.  
```
tomsquest/docker-radicale:3.1.8.2 (alpine 3.17.3)
=================================================
Total: 24 (UNKNOWN: 0, LOW: 3, MEDIUM: 6, HIGH: 8, CRITICAL: 7)
┌────────────────────────┬────────────────┬──────────┬───────────────────┬──────────────────┬─────────────────────────────────────────────────────────────┐
│        Library         │ Vulnerability  │ Severity │ Installed Version │  Fixed Version   │                            Title                            │
├────────────────────────┼────────────────┼──────────┼───────────────────┼──────────────────┼─────────────────────────────────────────────────────────────┤
│ curl                   │ CVE-2023-28319 │ HIGH …
```

chore: bump Alpine Version to 3.18.2

---

README.md

Since https://github.com/tomsquest/docker-radicale/pull/141, the docker image uses a `venv` for python.
Extending the docker images now requires using the venv's pip. This PR updates the README to reflect this change.

doc: update image extension instructions

---

README.md

I wrote some basic example of configuring htpasswd authentication to `docker-radicale`.

doc: add authentication config example

---

Dockerfile

fix: move pytz from global (alpine) to python venv

---

Dockerfile
README.md

feat: add python ldap3 for LDAP authentication

---

config

Fix #182 
Radicale 3.5.0 defaults to `denyall` as the auth type, meaning no access to Radicale until a proper auth type is setup.
This PR set the auth type to `none` as it was in previous released.

fix: auth is set to deny all by default, setting it to `none`
